pub mod geometry;
pub mod color;
pub mod matrix;
pub mod layer;
pub mod tool;
pub mod document;
pub mod advanced;
pub mod composite;
pub mod camera;
pub mod text;
pub mod audio;
pub mod shortcut;
pub mod history;

pub use geometry::{Point, Size, Rect, Vector2D};
pub use color::{Color8, Color16, ColorF};
pub use matrix::{Matrix2D};
pub use layer::{uuid, LayerId, LayerType, BlendMode, LayerBase, RasterFrame, RasterLayer, StrokePoint, Stroke, VectorFrame, VectorLayer, CameraLayer, TextLayer, SoundLayer, Layer};
pub use tool::{ToolId, ToolType, MouseButton, ModifierKey, ToolEvent, ToolContext, ToolAction, ToolActionType, Tool, CursorShape, BrushSettings, LineProcessingSettings, LinePushSettings, LineVolumeSettings, SmartDrawSettings, StampSettings, DustSettings, DustMode};
pub use document::{Timeline, DocumentSettings, Document, Project};
pub use composite::{blend_pixels, blend_pixels_rgba, composite_layers, apply_mask, create_checkerboard, fill_rect, draw_circle, draw_line, flood_fill};
pub use camera::{MotionBlurType, CameraKey, MotionBlurSettings, CameraTrack, Resolution, CameraLayerData, apply_camera_transform, composite_with_motion_blur};
pub use text::{FontWeight, FontStyle, TextAlignment, TextVerticalAlignment, TextDecoration, TextStyle, TextShadow, TextStroke, TextRun, TextLayerData, TextLine, rasterize_text};
pub use audio::{AudioFormat, AudioInfo, AudioClip, SoundLayerData, SoundClipPosition, AudioMixer, AudioMixerLayer, AudioEffect, EqBand};
pub use shortcut::{KeyCode, KeyModifiers, Shortcut, ShortcutAction, ShortcutBinding, ShortcutManager};
pub use history::{History};
